# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
_codemedo:
    resource: "@AqpglugCodemedoBundle/Resources/config/routing.yml"
